server:
  port: 9091
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=core
    username: postgres
    password: password


mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.nt
  type-handlers-package: com.nt.hash